package flashbuy.dao;

import flashbuy.dataobject.UserPassword;

public interface UserPasswordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_pswd
     *
     * @mbg.generated Thu Jan 16 01:12:07 PST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_pswd
     *
     * @mbg.generated Thu Jan 16 01:12:07 PST 2020
     */
    int insert(UserPassword record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_pswd
     *
     * @mbg.generated Thu Jan 16 01:12:07 PST 2020
     */
    int insertSelective(UserPassword record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_pswd
     *
     * @mbg.generated Thu Jan 16 01:12:07 PST 2020
     */
    UserPassword selectByPrimaryKey(Integer id);

    UserPassword selectByUserId(Integer userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_pswd
     *
     * @mbg.generated Thu Jan 16 01:12:07 PST 2020
     */
    int updateByPrimaryKeySelective(UserPassword record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_pswd
     *
     * @mbg.generated Thu Jan 16 01:12:07 PST 2020
     */
    int updateByPrimaryKey(UserPassword record);
}