package flashbuy.dataobject;

public class UserPassword {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_pswd.id
     *
     * @mbg.generated Thu Jan 16 01:12:07 PST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_pswd.encrp_pswd
     *
     * @mbg.generated Thu Jan 16 01:12:07 PST 2020
     */
    private String encrpPswd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_pswd.user_id
     *
     * @mbg.generated Thu Jan 16 01:12:07 PST 2020
     */
    private Integer userId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_pswd.id
     *
     * @return the value of user_pswd.id
     *
     * @mbg.generated Thu Jan 16 01:12:07 PST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_pswd.id
     *
     * @param id the value for user_pswd.id
     *
     * @mbg.generated Thu Jan 16 01:12:07 PST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_pswd.encrp_pswd
     *
     * @return the value of user_pswd.encrp_pswd
     *
     * @mbg.generated Thu Jan 16 01:12:07 PST 2020
     */
    public String getEncrpPswd() {
        return encrpPswd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_pswd.encrp_pswd
     *
     * @param encrpPswd the value for user_pswd.encrp_pswd
     *
     * @mbg.generated Thu Jan 16 01:12:07 PST 2020
     */
    public void setEncrpPswd(String encrpPswd) {
        this.encrpPswd = encrpPswd == null ? null : encrpPswd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_pswd.user_id
     *
     * @return the value of user_pswd.user_id
     *
     * @mbg.generated Thu Jan 16 01:12:07 PST 2020
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_pswd.user_id
     *
     * @param userId the value for user_pswd.user_id
     *
     * @mbg.generated Thu Jan 16 01:12:07 PST 2020
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }
}